#!/bin/bash
# vim: set sw=4 ts=4 et :

set -x

systems=(
    plucky # OK
    noble  # OK
    jammy  # cloud-init status --wait forever, OK with lp-1878225 workaround
    focal  # no use_pty by default, need use_pty sudoers cfg
    bionic # no use_pty by default, need use_pty sudoers cfg
    # xenial # cloud-init status --wait forever, sys-v init handling
    # trusty # cloud-init status not supported
)

for system in ${systems[@]}; do
    ../../oe --launch -s $system ./shell-test
done
