// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPTransporter is an autogenerated mock type for the HTTPTransporter type
type MockHTTPTransporter struct {
	mock.Mock
}

// RoundTrip provides a mock function with given fields: _a0
func (_m *MockHTTPTransporter) RoundTrip(_a0 *http.Request) (*http.Response, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RoundTrip")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transport provides a mock function with no fields
func (_m *MockHTTPTransporter) Transport() *http.Transport {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Transport")
	}

	var r0 *http.Transport
	if rf, ok := ret.Get(0).(func() *http.Transport); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Transport)
		}
	}

	return r0
}

// NewMockHTTPTransporter creates a new instance of MockHTTPTransporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPTransporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPTransporter {
	mock := &MockHTTPTransporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
